services:
  db:
    build: .  # Build custom image with TimescaleDB + PostGIS
    container_name: ${DB_CONTAINER_NAME}
    shm_size: 2gb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}
      POSTGRES_SHARED_BUFFERS: ${DB_SHARED_BUFFERS}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${DB_DATA_PATH}:/var/lib/postgresql/data"  # Data persistence
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"  # Database initialization script
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=timescaledb"  # Required for TimescaleDB
      - "-c"
      - "max_connections=${DB_MAX_CONNECTIONS}"
      - "-c"
      - "shared_buffers=${DB_SHARED_BUFFERS}"
      - "-c"
      - "effective_cache_size=${DB_EFFECTIVE_CACHE_SIZE}"
      - "-c"
      - "maintenance_work_mem=${DB_MAINTENANCE_WORK_MEM}"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=300"
      - "-c"
      - "work_mem=${DB_WORK_MEM}"  # ✅ Fixed: was 2759kB
      - "-c"
      - "huge_pages=off"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=20"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=20"
      - "-c"
      - "max_parallel_maintenance_workers=4"
      - "-c"
      - "track_activities=on"
      - "-c"
      - "track_counts=on"
      - "-c"
      - "listen_addresses=*"
    restart: always

  pgcat:
    image: ghcr.io/postgresml/pgcat:latest
    container_name: ${PGCAT_CONTAINER_NAME}
    restart: always
    ports:
      - "${PGCAT_PORT}:6432"
      - "9930:9930"  # Admin interface
      - "9931:9931"  # Prometheus metrics
    volumes:
      - ./pgcat/pgcat.toml:/etc/pgcat/pgcat.toml:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: ${POSTGRES_EXPORTER_CONTAINER_NAME}
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "${POSTGRES_EXPORTER_PORT}:9187"
    restart: always
    depends_on:
      - db

volumes:
  data_timescale: